[build]
  publish = "."
  command = "pip install -r requirements.txt && python setup_nltk.py"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
